### ISSUE TITLE
java.lang.IllegalStateException: Unable to update texture contents (see logcat for details)

### ISSUE THREAD

**Issue by CFD08Joshua** [JYangkai/MediaDemo#1]
我將 video view 加入到 adapter 搭配 ViewPager 達到左右橫滑效果，但返回上部影片時，都會報錯

E/: [SurfaceTexture-0-31427-1] checkAndUpdateEglState: invalid current EGLContext
E/BufferQueueProducer: [SurfaceTexture-0-31427-4](id:7ac300000004,api:0,p:-1,c:31427) disconnect: not connected (req=1)
W/libEGL: EGLNativeWindowType 0x7e00b51010 disconnect failed
    
    --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: GLThread 7484
    Process: , PID: 31427
    java.lang.IllegalStateException: Unable to update texture contents (see logcat for details)
        at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
        at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:248)
        at com.yk.media.opengles.render.base.BaseOesRender.onDrawPre(BaseOesRender.java:99)
        at com.yk.media.opengles.render.base.BaseRender.onDraw(BaseRender.java:188)
        at com.yk.media.opengles.render.base.BaseOesRender.onDrawSelf(BaseOesRender.java:139)
        at com.yk.media.opengles.render.OesRender.onDraw(OesRender.java:53)
        at com.yk.media.opengles.view.base.EGLTextureView$GLThread.guardedRun(EGLTextureView.java:1455)
        at com.yk.media.opengles.view.base.EGLTextureView$GLThread.run(EGLTextureView.java:1165)

**Comment by bhavin-qfonapp** [comment]
Found any solution?
